package com.lyk.coursearrange.auth.service.impl;

import com.lyk.coursearrange.auth.model.LoginUser;
import com.lyk.coursearrange.auth.service.AuthViewStrategy;
import com.lyk.coursearrange.common.constants.SystemConstants;
import com.lyk.coursearrange.system.rbac.vo.MenuTreeVO;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * 管理员菜单权限策略。
 */
@Component
public class AdminAuthViewStrategy implements AuthViewStrategy {

    @Override
    public boolean supports(String roleCode) {
        return SystemConstants.RoleCode.ADMIN.equals(roleCode);
    }

    @Override
    public List<String> buildPermissions(LoginUser loginUser) {
        return List.of(
                "page:dashboard:view",
                "page:course-plan:view",
                "page:schedule:view",
                "page:base-data:view",
                "page:campus:view",
                "page:college:view",
                "page:stage:view",
                "page:config:view",
                "page:rbac:view",
                "btn:config:edit",
                "btn:timetable:drag-adjust"
        );
    }

    @Override
    public List<MenuTreeVO> buildMenus(LoginUser loginUser) {
        return List.of(
                MenuTreeVO.builder()
                        .id(1L)
                        .menuCode("dashboard")
                        .parentId(0L)
                        .menuName("工作台")
                        .menuType("MENU")
                        .routeName("Dashboard")
                        .routePath("/dashboard")
                        .componentPath("views/dashboard/DashboardView.vue")
                        .icon("House")
                        .permissionCode("page:dashboard:view")
                        .isHidden(0)
                        .isKeepAlive(0)
                        .sortNo(1)
                        .children(List.of())
                        .build(),
                MenuTreeVO.builder()
                        .id(2L)
                        .menuCode("course-plan")
                        .parentId(0L)
                        .menuName("排课任务")
                        .menuType("MENU")
                        .routeName("CoursePlan")
                        .routePath("/course-plan")
                        .componentPath("views/course/CoursePlanView.vue")
                        .icon("Tickets")
                        .permissionCode("page:course-plan:view")
                        .isHidden(0)
                        .isKeepAlive(0)
                        .sortNo(2)
                        .children(List.of())
                        .build(),
                MenuTreeVO.builder()
                        .id(3L)
                        .menuCode("schedule")
                        .parentId(0L)
                        .menuName("课表管理")
                        .menuType("MENU")
                        .routeName("Schedule")
                        .routePath("/schedule")
                        .componentPath("views/course/ScheduleView.vue")
                        .icon("Calendar")
                        .permissionCode("page:schedule:view")
                        .isHidden(0)
                        .isKeepAlive(0)
                        .sortNo(3)
                        .children(List.of())
                        .build(),
                MenuTreeVO.builder()
                        .id(4L)
                        .menuCode("base-data")
                        .parentId(0L)
                        .menuName("基础数据")
                        .menuType("MENU")
                        .routeName("BaseData")
                        .routePath("/base-data")
                        .componentPath("views/base/BaseDataView.vue")
                        .icon("Collection")
                        .permissionCode("page:base-data:view")
                        .isHidden(0)
                        .isKeepAlive(0)
                        .sortNo(4)
                        .children(List.of())
                        .build(),
                MenuTreeVO.builder()
                        .id(5L)
                        .menuCode("organization")
                        .parentId(0L)
                        .menuName("组织架构")
                        .menuType("CATALOG")
                        .routeName("Organization")
                        .routePath("/organization")
                        .componentPath("layouts/BasicLayout.vue")
                        .icon("OfficeBuilding")
                        .isHidden(0)
                        .isKeepAlive(0)
                        .sortNo(5)
                        .children(List.of(
                                MenuTreeVO.builder()
                                        .id(51L)
                                        .menuCode("campus")
                                        .parentId(5L)
                                        .menuName("校区管理")
                                        .menuType("MENU")
                                        .routeName("CampusPage")
                                        .routePath("/organization/campus")
                                        .componentPath("views/organization/CampusView.vue")
                                        .permissionCode("page:campus:view")
                                        .isHidden(0)
                                        .isKeepAlive(0)
                                        .sortNo(1)
                                        .children(List.of())
                                        .build(),
                                MenuTreeVO.builder()
                                        .id(52L)
                                        .menuCode("college")
                                        .parentId(5L)
                                        .menuName("学院管理")
                                        .menuType("MENU")
                                        .routeName("CollegePage")
                                        .routePath("/organization/college")
                                        .componentPath("views/organization/CollegeView.vue")
                                        .permissionCode("page:college:view")
                                        .isHidden(0)
                                        .isKeepAlive(0)
                                        .sortNo(2)
                                        .children(List.of())
                                        .build(),
                                MenuTreeVO.builder()
                                        .id(53L)
                                        .menuCode("stage")
                                        .parentId(5L)
                                        .menuName("学段管理")
                                        .menuType("MENU")
                                        .routeName("StagePage")
                                        .routePath("/organization/stage")
                                        .componentPath("views/organization/StageView.vue")
                                        .permissionCode("page:stage:view")
                                        .isHidden(0)
                                        .isKeepAlive(0)
                                        .sortNo(3)
                                        .children(List.of())
                                        .build()
                        ))
                        .build(),
                MenuTreeVO.builder()
                        .id(6L)
                        .menuCode("system")
                        .parentId(0L)
                        .menuName("系统管理")
                        .menuType("CATALOG")
                        .routeName("SystemManage")
                        .routePath("/system")
                        .componentPath("layouts/BasicLayout.vue")
                        .icon("Setting")
                        .isHidden(0)
                        .isKeepAlive(0)
                        .sortNo(6)
                        .children(List.of(
                                MenuTreeVO.builder()
                                        .id(61L)
                                        .menuCode("system-config")
                                        .parentId(6L)
                                        .menuName("系统配置")
                                        .menuType("MENU")
                                        .routeName("SystemConfigPage")
                                        .routePath("/system/config")
                                        .componentPath("views/system/SystemConfigView.vue")
                                        .icon("Setting")
                                        .permissionCode("page:config:view")
                                        .isHidden(0)
                                        .isKeepAlive(0)
                                        .sortNo(1)
                                        .children(List.of())
                                        .build(),
                                MenuTreeVO.builder()
                                        .id(62L)
                                        .menuCode("system-rbac")
                                        .parentId(6L)
                                        .menuName("权限管理")
                                        .menuType("MENU")
                                        .routeName("RbacManagePage")
                                        .routePath("/system/rbac")
                                        .componentPath("views/system/RbacManageView.vue")
                                        .icon("Lock")
                                        .permissionCode("page:rbac:view")
                                        .isHidden(0)
                                        .isKeepAlive(0)
                                        .sortNo(2)
                                        .children(List.of())
                                        .build()
                        ))
                        .build(),
                MenuTreeVO.builder()
                        .id(7L)
                        .menuCode("guide")
                        .parentId(0L)
                        .menuName("重构说明")
                        .menuType("MENU")
                        .routeName("Guide")
                        .routePath("/guide")
                        .componentPath("views/system/SystemGuideView.vue")
                        .icon("Document")
                        .isHidden(0)
                        .isKeepAlive(0)
                        .sortNo(7)
                        .children(List.of())
                        .build()
        );
    }
}
