USE `course_arrange_v2`;

CREATE TABLE IF NOT EXISTS `sch_task` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `task_code` varchar(32) NOT NULL COMMENT '排课任务编码',
  `school_year_id` bigint NOT NULL COMMENT '学年ID',
  `term_id` bigint NOT NULL COMMENT '学期ID',
  `campus_id` bigint DEFAULT NULL COMMENT '校区ID',
  `college_id` bigint DEFAULT NULL COMMENT '学院ID',
  `stage_id` bigint NOT NULL COMMENT '学段ID',
  `grade_id` bigint DEFAULT NULL COMMENT '年级ID',
  `major_id` bigint DEFAULT NULL COMMENT '专业ID',
  `admin_class_id` bigint DEFAULT NULL COMMENT '行政班ID',
  `teaching_class_id` bigint DEFAULT NULL COMMENT '教学班ID',
  `course_id` bigint NOT NULL COMMENT '课程ID',
  `teacher_id` bigint NOT NULL COMMENT '教师ID',
  `student_count` int NOT NULL DEFAULT 0 COMMENT '上课人数',
  `week_hours` int NOT NULL DEFAULT 0 COMMENT '周课时',
  `total_hours` int NOT NULL DEFAULT 0 COMMENT '总课时',
  `need_continuous` tinyint NOT NULL DEFAULT 0 COMMENT '是否连堂',
  `continuous_size` int NOT NULL DEFAULT 1 COMMENT '连堂节数',
  `need_fixed_room` tinyint NOT NULL DEFAULT 0 COMMENT '是否固定教室',
  `fixed_room_id` bigint DEFAULT NULL COMMENT '固定教室ID',
  `need_fixed_time` tinyint NOT NULL DEFAULT 0 COMMENT '是否固定时间',
  `fixed_weekday_no` int DEFAULT NULL COMMENT '固定星期',
  `fixed_period_no` int DEFAULT NULL COMMENT '固定节次',
  `priority_level` int NOT NULL DEFAULT 5 COMMENT '优先级',
  `allow_conflict` tinyint NOT NULL DEFAULT 0 COMMENT '是否允许冲突排课',
  `task_status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '任务状态',
  `source_type` varchar(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sch_task_code` (`task_code`),
  KEY `idx_sch_task_scope` (`term_id`, `campus_id`, `college_id`, `stage_id`),
  KEY `idx_sch_task_class` (`admin_class_id`, `teaching_class_id`),
  KEY `idx_sch_task_teacher_course` (`teacher_id`, `course_id`),
  KEY `idx_sch_task_status` (`task_status`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='排课任务表';

CREATE TABLE IF NOT EXISTS `sch_schedule_result` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `run_log_id` bigint DEFAULT NULL COMMENT '所属执行批次ID',
  `task_id` bigint NOT NULL COMMENT '排课任务ID',
  `school_year_id` bigint NOT NULL COMMENT '学年ID',
  `term_id` bigint NOT NULL COMMENT '学期ID',
  `campus_id` bigint DEFAULT NULL COMMENT '校区ID',
  `college_id` bigint DEFAULT NULL COMMENT '学院ID',
  `stage_id` bigint NOT NULL COMMENT '学段ID',
  `grade_id` bigint DEFAULT NULL COMMENT '年级ID',
  `admin_class_id` bigint DEFAULT NULL COMMENT '行政班ID',
  `teaching_class_id` bigint DEFAULT NULL COMMENT '教学班ID',
  `course_id` bigint NOT NULL COMMENT '课程ID',
  `teacher_id` bigint NOT NULL COMMENT '教师ID',
  `classroom_id` bigint DEFAULT NULL COMMENT '教室ID',
  `weekday_no` int NOT NULL COMMENT '星期',
  `period_no` int NOT NULL COMMENT '节次',
  `week_range_type` varchar(32) NOT NULL DEFAULT 'ALL' COMMENT '周次类型',
  `week_range_text` varchar(128) DEFAULT NULL COMMENT '自定义周次描述',
  `is_locked` tinyint NOT NULL DEFAULT 0 COMMENT '是否锁定',
  `source_type` varchar(32) NOT NULL DEFAULT 'AUTO' COMMENT '来源',
  `conflict_flag` tinyint NOT NULL DEFAULT 0 COMMENT '是否存在冲突标记',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_sch_schedule_result_task` (`task_id`),
  KEY `idx_sch_schedule_result_class` (`term_id`, `admin_class_id`, `weekday_no`, `period_no`),
  KEY `idx_sch_schedule_result_teacher` (`term_id`, `teacher_id`, `weekday_no`, `period_no`),
  KEY `idx_sch_schedule_result_classroom` (`term_id`, `classroom_id`, `weekday_no`, `period_no`),
  KEY `idx_sch_schedule_result_teaching_class` (`term_id`, `teaching_class_id`, `weekday_no`, `period_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='课表结果表';
