USE `course_arrange_v2`;

CREATE TABLE IF NOT EXISTS `sch_schedule_run_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `run_code` varchar(32) NOT NULL COMMENT '执行批次编码',
  `term_id` bigint NOT NULL COMMENT '学期ID',
  `campus_id` bigint DEFAULT NULL COMMENT '校区ID',
  `college_id` bigint DEFAULT NULL COMMENT '学院ID',
  `stage_id` bigint DEFAULT NULL COMMENT '学段ID',
  `run_type` varchar(32) NOT NULL DEFAULT 'AUTO' COMMENT '执行类型',
  `algorithm_type` varchar(32) NOT NULL DEFAULT 'GENETIC' COMMENT '算法类型',
  `task_total` int NOT NULL DEFAULT 0 COMMENT '任务总数',
  `task_success` int NOT NULL DEFAULT 0 COMMENT '成功排入数量',
  `task_failed` int NOT NULL DEFAULT 0 COMMENT '失败数量',
  `run_status` varchar(32) NOT NULL DEFAULT 'RUNNING' COMMENT '执行状态',
  `failure_reason` varchar(500) DEFAULT NULL COMMENT '失败原因',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
  `operator_user_id` bigint DEFAULT NULL COMMENT '操作人用户ID',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sch_schedule_run_log_code` (`run_code`),
  KEY `idx_sch_schedule_run_log_scope` (`term_id`, `campus_id`, `college_id`, `stage_id`),
  KEY `idx_sch_schedule_run_log_status` (`run_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='排课执行日志表';

CREATE TABLE IF NOT EXISTS `sch_schedule_adjust_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `adjust_code` varchar(32) NOT NULL COMMENT '调课编码',
  `term_id` bigint NOT NULL COMMENT '学期ID',
  `source_result_id` bigint NOT NULL COMMENT '原课表结果ID',
  `target_result_id` bigint DEFAULT NULL COMMENT '目标课表结果ID',
  `adjust_type` varchar(32) NOT NULL COMMENT '调课类型',
  `before_weekday_no` int DEFAULT NULL COMMENT '调整前星期',
  `before_period_no` int DEFAULT NULL COMMENT '调整前节次',
  `before_classroom_id` bigint DEFAULT NULL COMMENT '调整前教室ID',
  `after_weekday_no` int DEFAULT NULL COMMENT '调整后星期',
  `after_period_no` int DEFAULT NULL COMMENT '调整后节次',
  `after_classroom_id` bigint DEFAULT NULL COMMENT '调整后教室ID',
  `adjust_reason` varchar(255) DEFAULT NULL COMMENT '调课原因',
  `operator_user_id` bigint NOT NULL COMMENT '操作人用户ID',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sch_schedule_adjust_log_code` (`adjust_code`),
  KEY `idx_sch_schedule_adjust_log_term` (`term_id`, `operator_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='调课日志表';
